git:
  autoFetch: false
  pagers:
    - colorArg: always
      pager: delta --light --paging=never --side-by-side
gui:
  theme:
    lightTheme: true
    activeBorderColor:
      - '#1e66f5' # Blue
      - bold
    inactiveBorderColor:
      - '#9ca0b0' # Overlay0
    optionsTextColor:
      - '#1e66f5' # Blue
    selectedLineBgColor:
      - '#ccd0da' # Surface0
    selectedRangeBgColor:
      - '#ccd0da' # Surface0
    cherryPickedCommitBgColor:
      - '#bcc0cc' # Surface1
    cherryPickedCommitFgColor:
      - '#1e66f5' # Blue
    unstagedChangesColor:
      - '#d20f39' # Red
    defaultFgColor:
      - '#4c4f69' # Text
    searchingActiveBorderColor:
      - '#df8e1d' # Yellow
os:
  shell: "zsh"
  shellArg: "-c"
customCommands:
  - key: "G"
    description: "AI commit message"
    context: "files"
    command: 'ai-commit > /tmp/commit-msg && git commit -eF /tmp/commit-msg'
    loadingText: "Generating commit message..."
    output: terminal
